[project]
name = "gnn-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "omegaconf>=2.3.0",
    "pandas>=2.3.3",
    "torch>=2.9.1",
    "torch-geometric>=2.7.0",
]
