dataset:
  name: fb15k237

model:
  name: DistMult
  hidden_channels: 50
  margin: 1.0

training:
  lr: 0.0001
  epochs: 500
  batch_size: 2048
  log_every: 50

evaluation:
  batch_size: 20000
  k: 10

seed: 42
